//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
        public string ConfirmPwd { get; set; }
        public string Uemail { get; set; }
        public string Salary { get; set; }
    }
}
